version: '3'

services:
  # mmiwg2s-service:
  #   image: mmiwg2s-submissions:latest
  #   build:
  #     context: ./
  #     ports:
  #       - 3000:3000
  #     depends_on:
  #       - "database"

  database:
    image: mongo:3.6
    container_name: 'submission-database'
    environment:
      # - MONGO_INTIDB_DATABASE=mmiwg2s-submission-database
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017